#!/usr/bin/env bash

# This file is used to run "tmux-test" framework tests.

# "setup" script is needed to run the tests, but it overrides some working dir
# files. To address that, "setup" is run before the tests and it's actions are
# undone after.

ENV="$1"

main() {
	lib/tmux-test/setup
	if [ "$ENV" == "travis" ]; then
		./tests/run_tests_in_isolation
	else
		./run_tests
	fi
	local exit_value=$?
	lib/tmux-test/setup "undo"
	exit "$exit_value"
}
main
