#!/usr/bin/env bash

# invoke this script from your projects root directory

CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

add_files_to_gitignore() {
	grep -q "^run_tests$" .gitignore 2>/dev/null || echo "run_tests" >> .gitignore
	grep -q "run_tests_in_isolation" .gitignore 2>/dev/null || echo "run_tests_in_isolation"      >> .gitignore
}

symlink_user_test_runner() {
	ln -sf lib/tmux-test/run_tests run_tests
}

create_directory_for_tests() {
	mkdir -p tests/
}

symlink_internal_test_runner() {
	ln -sf ../lib/tmux-test/tests/run_tests_in_isolation tests/run_tests_in_isolation
}

symlink_test_helpers() {
	ln -sf ../lib/tmux-test/tests/helpers tests/helpers
}

copy_travis_yml() {
	cp lib/tmux-test/.travis.yml .travis.yml
}

main() {
	add_files_to_gitignore
	symlink_user_test_runner
	create_directory_for_tests
	symlink_internal_test_runner
	symlink_test_helpers
	copy_travis_yml
}
main

